template_path: UHM_models/mean_nme_fcolor_b.ply

model:
  sampling:
    type: r_weighted                                                            # {basic, r_weighted}
    global_factors: [4, 4, 4, 4]